#!/bin/sh

# Set monitor workspaces
bspc monitor -d 1 2 3 4 5 6 7 8 9

# Window appearance
bspc config border_width 1
bspc config window_gap 1
bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer true

# Padding configuration
bspc config top_padding 0
bspc config left_padding 0
bspc config right_padding 0
bspc config bottom_padding 23

# Border colors
bspc config normal_border_color "#16161e"
bspc config focused_border_color "#414868"
bspc config urgent_border_color "#f7768e"

# Rules for floating windows
bspc rule -a "Galculator" state=floating
bspc rule -a "Gpick" state=floating
bspc rule -a "Gufw.py" state=floating
bspc rule -a "Surf" state=tiled
bspc rule -a "flameshot" state floating
bpsc rule -a "pomotroid" state=floating
bspc rule -a "*:Browser:*" state=floating
bspc rule -a "*:Places:*" state=floating
bspc rule -a "*:Toolkit:*" state=floating sticky=on
bspc rule -a "*:*:Picture in picture" state=floating sticky=on

# Autostart
run() {
	if ! pgrep -f "$1"; then
		"$@" &
	fi
}

run setxkbmap latam
run touchpad_config --enable
run xset r rate 300 50 -b
run ~/.fehbg
run sxhkd -c "$HOME/.config/bspwm/sxhkdrc"
run mate-polkit
run picom
run redshift LAT:LON
run xsetroot -cursor_name left_ptr
run unclutter
run polybar -c $HOME/.config/bspwm/polybar/config.ini bspwm
